version: "3.7"

x-template: &template
  image: consul
  entrypoint: ping
  command: baidu.com

services:
  g1:
    <<: *template
    ports:
      - 8003:8001
    labels:
      - aginx.domain=g1.aginx.io
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  g2:
    <<: *template
    labels:
      - aginx.domain=g2.aginx.io
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints: [node.role == worker]