version: "3.7"

services:
  aginx-allinone:
    image: xhaiker/aginx:v2.0.0
    container_name: allinone
    ports:
      - 80:80
      - 443:443
      - 8011:8011
    environment:
      AGINX_BIND: 0.0.0.0:8011
      AGINX_LOG_LEVEL: debug
      AGINX_AUTH: aginx=aginx
      AGINX_EXPOSE: api.aginx.io
      AGINX_REGISTRY: docker://var/run/docker.sock?ip=node1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      aginx.domain.0: http://web.aginx.io
